https://bugs.python.org/issue41660